D55DD875# It's for convenience and nightly-testing with people
FR56
          name: gpth-nightly-${{ runner.os }}
          path: ./${{ steps.exe_name.outputs.name }}
          if-no-files-found: error